from pathlib import Path
from utils import logger

def generate_project(project_name: str, base_path: str = "."):
    """
    Generates a basic project directory structure and starter files.
    """
    base_dir = Path(base_path) / project_name
    
    if base_dir.exists():
        logger.error(f"Error: Directory '{base_dir}' already exists.")
        return
        
    directories = [
        "src",
        "tests",
        "docs"
    ]
    
    files = {
        "README.md": f"# {project_name}\n\nA new project generated by cscli.\n",
        "main.py": 'def main():\n    print("Hello from main!")\n\nif __name__ == "__main__":\n    main()\n',
        ".gitignore": "__pycache__/\n*.pyc\n.env\nvenv/\n",
        "src/__init__.py": "",
        "tests/__init__.py": ""
    }
    
    try:
        # Create base directory
        base_dir.mkdir(parents=True, exist_ok=False)
        logger.info(f"Created project folder: {base_dir}")
        
        # Create subdirectories
        for d in directories:
            dir_path = base_dir / d
            dir_path.mkdir()
            logger.info(f"Created directory: {dir_path}")
            
        # Create starter files
        for filename, content in files.items():
            file_path = base_dir / filename
            file_path.write_text(content, encoding="utf-8")
            logger.info(f"Created file: {file_path}")
            
        logger.info(f"Project '{project_name}' generated successfully.")
    except Exception as e:
        logger.error(f"Failed to generate project: {e}")
